<?php
// Auto-generated by the theme — re-run `wp lqx regenerate-block-manifest` after adding/editing block.json files.
// WP 6.7+ block metadata collection: avoids per-request glob + JSON decode.
return array (
  'accordion' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix accordion block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/accordion',
    'title' => 'Lyquix Accordion',
    'description' => 'An Accordion block',
    'category' => 'lqx-content-blocks',
    'icon' => 'menu',
    'keywords' => 
    array (
      0 => 'accordion',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'accordion.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'accordion-item' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix accordion item block definition',
      2 => '*',
      3 => '* @version     3.1.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/accordion-item',
    'title' => 'Lyquix Accordion Item',
    'description' => 'An Accordion Item block',
    'category' => 'lqx-content-blocks',
    'icon' => 'menu',
    'keywords' => 
    array (
      0 => 'accordion',
      1 => 'accordion-item',
    ),
    'acf' => 
    array (
      'mode' => 'preview',
      'renderTemplate' => 'accordion-item.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'jsx' => true,
    ),
    'parent' => 
    array (
      0 => 'lqx/accordion-plus',
    ),
    'usesContext' => 
    array (
      0 => 'acf/fields',
    ),
  ),
  'accordion-plus' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix accordion plus block definition',
      2 => '*',
      3 => '* @version     3.1.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/accordion-plus',
    'title' => 'Lyquix Accordion Plus',
    'description' => 'An Accordion Plus block',
    'category' => 'lqx-content-blocks',
    'icon' => 'menu',
    'keywords' => 
    array (
      0 => 'accordion',
      1 => 'plus',
    ),
    'acf' => 
    array (
      'mode' => 'preview',
      'renderTemplate' => 'accordion-plus.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
    ),
    'providesContext' => 
    array (
      'acf/fields' => 'data',
    ),
  ),
  'banner' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix banner block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/banner',
    'title' => 'Lyquix Banner',
    'description' => 'A banner block',
    'category' => 'lqx-content-blocks',
    'icon' => 'format-image',
    'keywords' => 
    array (
      0 => 'banner',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'banner.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'cards' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix cards block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/cards',
    'title' => 'Lyquix Cards',
    'description' => 'An cards block',
    'category' => 'lqx-content-blocks',
    'icon' => 'screenoptions',
    'keywords' => 
    array (
      0 => 'cards',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'cards.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'filters' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix cards block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/filters',
    'title' => 'Lyquix Filters',
    'description' => 'A list of items with filters',
    'category' => 'lqx-content-blocks',
    'icon' => 'list-view',
    'keywords' => 
    array (
      0 => 'cards',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'filters.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'gallery' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix gallery block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/gallery',
    'title' => 'Lyquix Gallery',
    'description' => 'A media gallery block with lightbox support',
    'category' => 'lqx-content-blocks',
    'icon' => 'format-gallery',
    'keywords' => 
    array (
      0 => 'media',
      1 => 'gallery',
      2 => 'lightbox',
      3 => 'image',
      4 => 'video',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'gallery.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'hero' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix hero banner block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/hero',
    'title' => 'Lyquix Hero',
    'description' => 'A banner block meant for the top of the page',
    'category' => 'lqx-content-blocks',
    'icon' => 'cover-image',
    'keywords' => 
    array (
      0 => 'banner',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'hero.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'logos' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix Logos block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/logos',
    'title' => 'Lyquix Logos',
    'description' => 'An logos block',
    'category' => 'lqx-content-blocks',
    'icon' => 'schedule',
    'keywords' => 
    array (
      0 => 'logos',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'logos.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'map' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix map block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/map',
    'title' => 'Lyquix Map',
    'description' => 'An locations block with support for a map and items list',
    'category' => 'lqx-content-blocks',
    'icon' => 'screenoptions',
    'keywords' => 
    array (
      0 => 'locations',
      1 => 'map',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'map.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'related-items' => 
  array (
    'name' => 'lqx/related-items',
    'title' => 'Lyquix Related Items',
    'description' => 'Display related posts based on shared taxonomy, field value, or parent relationship',
    'category' => 'lqx-content-blocks',
    'icon' => 'networking',
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'related-items.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'slider' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix slider block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/slider',
    'title' => 'Lyquix Slider',
    'description' => 'A slider block',
    'category' => 'lqx-content-blocks',
    'icon' => 'slides',
    'keywords' => 
    array (
      0 => 'slider',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'slider.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'tab-item' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix tab item block definition',
      2 => '*',
      3 => '* @version     3.1.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/tab-item',
    'title' => 'Lyquix Tab Item',
    'description' => 'A Tab Item block',
    'category' => 'lqx-content-blocks',
    'icon' => 'block-default',
    'keywords' => 
    array (
      0 => 'tabs',
      1 => 'tab-item',
    ),
    'acf' => 
    array (
      'mode' => 'preview',
      'renderTemplate' => 'tab-item.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'jsx' => true,
    ),
    'parent' => 
    array (
      0 => 'lqx/tabs-plus',
    ),
    'usesContext' => 
    array (
      0 => 'acf/fields',
    ),
  ),
  'tabs' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix tabs block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/tabs',
    'title' => 'Lyquix Tabs',
    'description' => 'A Tabs block',
    'category' => 'lqx-content-blocks',
    'icon' => 'block-default',
    'keywords' => 
    array (
      0 => 'tabs',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'tabs.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'tabs-plus' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix tabs plus block definition',
      2 => '*',
      3 => '* @version     3.1.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/tabs-plus',
    'title' => 'Lyquix Tabs Plus',
    'description' => 'A Tabs Plus block',
    'category' => 'lqx-content-blocks',
    'icon' => 'block-default',
    'keywords' => 
    array (
      0 => 'tabs',
    ),
    'acf' => 
    array (
      'mode' => 'preview',
      'renderTemplate' => 'tabs-plus.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
    ),
    'providesContext' => 
    array (
      'acf/fields' => 'data',
    ),
  ),
  'testimonial' => 
  array (
    '//' => 
    array (
      0 => '/**',
      1 => '* block.json - Lyquix testimonial block definition',
      2 => '*',
      3 => '* @version     3.2.0',
      4 => '* @package     wp_theme_lyquix',
      5 => '* @author      Lyquix',
      6 => '* @copyright   Copyright (C) 2015 - 2024 Lyquix',
      7 => '* @license     GNU General Public License version 2 or later',
      8 => '* @link        https://github.com/Lyquix/wp_theme_lyquix',
      9 => '*',
      10 => '*    .d8888b. 88888888888 .d88888b.  8888888b.   888',
      11 => '*   d88P  Y88b    888    d88P   Y88b 888   Y88b  888',
      12 => '*   Y88b.         888    888     888 888    888  888',
      13 => '*     Y888b.      888    888     888 888   d88P  888',
      14 => '*        Y88b.    888    888     888 8888888P    888',
      15 => '*          888    888    888     888 888         Y8P',
      16 => '*   Y88b  d88P    888    Y88b. .d88P 888            ',
      17 => '*     Y8888P      888      Y88888P   888         888',
      18 => '*',
      19 => '*  DO NOT MODIFY THIS FILE!',
      20 => '*/',
    ),
    'name' => 'lqx/testimonial',
    'title' => 'Lyquix Testimonial',
    'description' => 'A Testimonial block',
    'category' => 'lqx-content-blocks',
    'icon' => 'format-quote',
    'keywords' => 
    array (
      0 => 'testimonial',
    ),
    'acf' => 
    array (
      'mode' => 'edit',
      'renderTemplate' => 'testimonial.php',
    ),
    'supports' => 
    array (
      'align' => false,
      'anchor' => true,
      'mode' => false,
    ),
  ),
  'video' => 
  array (
    '$schema' => 'https://schemas.wp.org/trunk/block.json',
    'apiVersion' => 3,
    'name' => 'lqx/video',
    'title' => 'Lyquix Video',
    'category' => 'media',
    'icon' => 'format-video',
    'description' => 'Video block supporting YouTube/Vimeo URLs (via Lyqbox) and uploaded video files (inline or Lyqbox) with optional lazy load, hover play, and viewport play.',
    'supports' => 
    array (
      'align' => 
      array (
        0 => 'wide',
        1 => 'full',
      ),
      'html' => false,
      'anchor' => true,
    ),
    'attributes' => 
    array (
      'videoType' => 
      array (
        'type' => 'string',
        'default' => 'url',
      ),
      'videoUrl' => 
      array (
        'type' => 'string',
        'default' => '',
      ),
      'videoUploadId' => 
      array (
        'type' => 'number',
        'default' => 0,
      ),
      'videoUploadUrl' => 
      array (
        'type' => 'string',
        'default' => '',
      ),
      'videoUploadMime' => 
      array (
        'type' => 'string',
        'default' => '',
      ),
      'posterId' => 
      array (
        'type' => 'number',
        'default' => 0,
      ),
      'posterUrl' => 
      array (
        'type' => 'string',
        'default' => '',
      ),
      'caption' => 
      array (
        'type' => 'string',
        'default' => '',
      ),
      'openInLyqbox' => 
      array (
        'type' => 'boolean',
        'default' => false,
      ),
      'lazyLoad' => 
      array (
        'type' => 'boolean',
        'default' => false,
      ),
      'hoverPlay' => 
      array (
        'type' => 'boolean',
        'default' => false,
      ),
      'viewportPlay' => 
      array (
        'type' => 'boolean',
        'default' => false,
      ),
      'controls' => 
      array (
        'type' => 'boolean',
        'default' => true,
      ),
      'autoplay' => 
      array (
        'type' => 'boolean',
        'default' => false,
      ),
      'loop' => 
      array (
        'type' => 'boolean',
        'default' => false,
      ),
      'muted' => 
      array (
        'type' => 'boolean',
        'default' => false,
      ),
    ),
    'editorScript' => 'file:./editor.js',
    'render' => 'file:./render.php',
    'textdomain' => 'lyquix',
  ),
);
